name: farooqtariq7/freecodecamp
author:
  name: freder786
  email: tariq.farooq05@gmail.com
  url: null
copyright: 2015 freder786
description: 'The http://FreeCodeCamp.com open-source codebase and curriculum. Practice coding by helping nonprofits.'
